### ISSUE TITLE
UUID conflict

### ISSUE THREAD

**Issue by marucjmar** [DefactoSoftware/ex_cell#62]
Thank you for this wonderful library

I would ask for a change of dependency from `uuid` to `elixir_uuid`, because I have a conflict in the project.

```
Unchecked dependencies for environment test:
* uuid (Hex package)
  could not find an app file at "_build/test/lib/uuid/ebin/uuid.app". This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

 [Check my example](https://github.com/marucjmar/ex_cell/commit/00910bdbf156b00618e6c4f9b5638eeead310f60)
Thanks

**Comment by tarzan** [comment]
Thanks for reaching out, I've prepared a PR from you the change you applied. We'll probably merge it soon.

**Comment by sn3p** [comment]
@marucjmar thanks for reporting! New version has been released:
https://hex.pm/packages/ex_cell/0.0.14
