### ISSUE TITLE
Nested cells

### ISSUE THREAD

**Issue by szymon-krysztofiak-dev** [DefactoSoftware/ex_cell#69]
How to put index.js code in nested cells? I have something like this in my folder structure:

-cells
--transactions
---history
----index.js
----cell.ex
----template.html.slim

```
class HistoryCell extends Cell {
  initialize() {
    console.log(1)
  }
}

Builder.register(HistoryCell, "HistoryCell")

export default HistoryCell```

**Comment by szymon-krysztofiak-dev** [comment]
OK, I had to add `Builder.register(HistoryCell, "Transactions-HistoryCell")`

It is a pity that it is not in the documentation

**Comment by sn3p** [comment]
> OK, I had to add `Builder.register(HistoryCell, "Transactions-HistoryCell")`
> 
> It is a pity that it is not in the documentation

Ah yes, docs don't say anything about that. Will add it!

**Comment by sn3p** [comment]
Updated [README](https://github.com/DefactoSoftware/ex_cell#nested-cells), thanks for pointing this out :)
